### ISSUE TITLE
Error: allocating outside of page on multithreaded ba_alloc call

### ISSUE THREAD

**Issue by jramapuram** [arneg/GJAlloc#3]
I have a multithreaded application where I call `ba_alloc()` from multiple threads.
After repeated calls I have noticed that I receive this error.

The setup has:
- 20 blocks
- max of 102405

I keep track of every time i call `ba_alloc` (which is the 'allocated' value below).
The data I store is also rather small throughout (i.e. it is only 90 below).

After a while I receive this error:

``` bash
value len = 90 / max = 102405
allocated: 2
allocated: 2
ERROR at ./tgt/Darwin-x86_64/libgjalloc/include/gjalloc.h:463
./tgt/Darwin-x86_64/libgjalloc/include/gjalloc.h:463    about to allocate block 0x100000000 outside of page 0x106e00000[0x106e00028-0x106fdfce6].
```

Any thoughts? Do I need to mutex the `ba_alloc` calls?

**Comment by arneg** [comment]
Yes, the allocator is not thread safe, so you will somehow have to synchronize calls to it.
